name: .NET Build and Deploy with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t codeoperations:latest ./codeoperations/Dockerfile 

    - name: Run container
      run: docker run --rm codeoperations:latest
      
    - name: Check Container list for verification
      run: docker ps -a
