name: .NET Build and Deploy with Docker

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t codeoperations:latest -f ./codeoperations/Dockerfile ./codeoperations


    - name: Run container (deployment simulation)
      run: docker run -d --name codeoperations -p 8080:80 codeoperations:latest
      
    - name: Run container
      run: docker run --rm codeoperations:latest
      
    - name: Check Container list for verification
      run: docker ps -a
